import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import { resolve, dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const target = resolve(process.argv[2] || join(root, 'flujo'));
const files = {};
for (const area of ['client', 'server']) {
  const source = join(root, 'src', area), output = join(target, 'src/vendor/avatar', area);
  await mkdir(output, { recursive: true });
  for (const name of await readdir(source)) {
    const bytes = await readFile(join(source, name));
    await writeFile(join(output, name), bytes);
    files[`src/${area}/${name}`] = createHash('sha256').update(bytes).digest('hex');
  }
}
await mkdir(join(target, 'public'), { recursive: true });
const audio = await readFile(join(root, 'public/avatar-audio-capture.js'));
await writeFile(join(target, 'public/avatar-audio-capture.js'), audio);
files['public/avatar-audio-capture.js'] = createHash('sha256').update(audio).digest('hex');
await writeFile(join(target, 'src/vendor/avatar/PROVENANCE.json'), JSON.stringify({
  repository: 'https://github.com/flujo-app/flujo-avatar',
  policy: 'Generated by scripts/sync-flujo.mjs; edit source in flujo-avatar and resync.', files,
}, null, 2) + '\n');
console.log(`Synchronized ${Object.keys(files).length} avatar files to ${relative(root, target) || '.'}`);
